### ISSUE TITLE
Problème avec le csv Assemblée

### ISSUE THREAD

**Issue by alphoenix** [regardscitoyens/Collaborateurs-Parlement#1]
Le csv avec les données des collaborateurs de l'Assemblée a un petit souci sur la première ligne, mais ça ne fait rien aux lignes suivantes.

**Comment by RouxRC** [comment]
En fait si, ça avait un gros impact, le dernier collab de chaque député était rattaché au parlementaire suivant du coup :/
C'est corrigé, j'avais raté le commit qui a introduit le bug, espérons que le format de leur pdf ne rebouge pas encore (en gros les positions verticales des infos sur le parlementaire ne sont plus alignées avec celles des assistants mais sont juste un peu en dessous maintenant...)

**Comment by alphoenix** [comment]
Ahah, très bien. Je l'ai téléchargé avant que ça change pour suivre les parcours professionnels de tous ces gens après le changement ;) 
Merci d'avoir regardé si tard !

**Comment by RouxRC** [comment]
Le problème remonte au 1er avril apparemment (super blague merci...) : https://github.com/regardscitoyens/Collaborateurs-Parlement/commit/5aaa121559482ddb197f2da5ab657e14da45bde4

La dernière version valide avant l'actuelle est donc celle-ci du 7 mars : https://github.com/regardscitoyens/Collaborateurs-Parlement/blob/b8c812096495464b24bb3c22a59619af822cf075/data/liste_deputes_collaborateurs.csv

L'historique git dans le repo est donc faux pour ce fichier entre ces deux versions. Au vu des diffs du pdf, on a raté juste une version (celle du 1er avril donc) : https://github.com/regardscitoyens/Collaborateurs-Parlement/blob/5aaa121559482ddb197f2da5ab657e14da45bde4/pdfs/liste_deputes_collaborateurs.pdf

On peut régénérer les données correspondantes pour cette version à la main au besoin mais corriger dans le repo c un peu super relou :s
